# Failed simulation analysis

This notebook scans the Nextflow workdirs for the `gene_knockout_462KO_basal_operon_on_p3` run and summarizes failed simulation tasks by count and failure reason.

In [5]:
from pathlib import Path
from collections import Counter
import re
import pandas as pd

base = Path('/user/home/il22158/work/vEcoli/reading')
run_root = Path('/user/home/il22158/work/vEcoli/out/gene_knockout_462KO_basal_operon_on_p3/nextflow/nextflow_workdirs')

records = []
for exit_file in run_root.glob('*/*/.exitcode'):
    workdir = exit_file.parent
    try:
        exit_code = int(exit_file.read_text().strip())
    except ValueError:
        exit_code = None

    log_path = workdir / '.command.log'
    err_path = workdir / '.command.err'
    out_path = workdir / '.command.out'
    run_path = workdir / '.command.run'

    err_text = err_path.read_text(errors='replace') if err_path.exists() else ''
    log_text = log_path.read_text(errors='replace') if log_path.exists() else ''
    out_text = out_path.read_text(errors='replace') if out_path.exists() else ''
    run_text = run_path.read_text(errors='replace') if run_path.exists() else ''

    failed = exit_code not in (0, None)
    if not failed:
        continue

    combined = '\n'.join([err_text, log_text, out_text])
    reason = 'unknown'
    if 'Negative molecule levels not allowed' in combined:
        reason = 'Negative molecule levels not allowed'
    elif 'GLP_NOFEAS' in combined:
        reason = 'FBA infeasible (GLP_NOFEAS)'
    else:
        match = re.search(r'([A-Za-z0-9_.]+Error: .+)', combined)
        if match:
            reason = match.group(1)
        else:
            tail = [line.strip() for line in combined.splitlines() if line.strip()]
            if tail:
                reason = tail[-1]

    task_name = ''
    for line in run_text.splitlines():
        if line.startswith('### name:'):
            task_name = line.split(':', 1)[1].strip().strip("'")
            break

    records.append({
        'workdir': str(workdir),
        'exit_code': exit_code,
        'reason': reason,
        'task_name': task_name,
    })

failed_df = pd.DataFrame(records)

if failed_df.empty:
    print('No failed tasks found under the Nextflow workdir root.')
else:
    summary = (
        failed_df.groupby('reason')
        .size()
        .sort_values(ascending=False)
        .rename('failed_tasks')
        .reset_index()
    )
    display(summary)
    print(f'Total failed tasks: {len(failed_df)}')
    print('\nFailures by exit code:')
    display(failed_df['exit_code'].value_counts().sort_index().rename('failed_tasks').to_frame())
## Save to csv
summary.to_csv(f'{base}/failed_tasks_summary_p3.csv', index=False)

                                              reason  failed_tasks
0  IndexError: cannot do a non-empty take from an...           102
1  ecoli_master_sim.py: error: argument --initial...            31
2               Negative molecule levels not allowed            24
3                        FBA infeasible (GLP_NOFEAS)             7

Total failed tasks: 164

Failures by exit code:

           failed_tasks
exit_code
1                   133
2                    31

In [7]:
from pathlib import Path
from collections import Counter
import re
import pandas as pd

base = Path('/user/home/il22158/work/vEcoli/reading')
run_root = Path('/user/home/il22158/work/vEcoli/out/gene_knockout_462KO_basal_operon_on_p4/nextflow/nextflow_workdirs')

records = []
for exit_file in run_root.glob('*/*/.exitcode'):
    workdir = exit_file.parent
    try:
        exit_code = int(exit_file.read_text().strip())
    except ValueError:
        exit_code = None

    log_path = workdir / '.command.log'
    err_path = workdir / '.command.err'
    out_path = workdir / '.command.out'
    run_path = workdir / '.command.run'

    err_text = err_path.read_text(errors='replace') if err_path.exists() else ''
    log_text = log_path.read_text(errors='replace') if log_path.exists() else ''
    out_text = out_path.read_text(errors='replace') if out_path.exists() else ''
    run_text = run_path.read_text(errors='replace') if run_path.exists() else ''

    failed = exit_code not in (0, None)
    if not failed:
        continue

    combined = '\n'.join([err_text, log_text, out_text])
    reason = 'unknown'
    if 'Negative molecule levels not allowed' in combined:
        reason = 'Negative molecule levels not allowed'
    elif 'GLP_NOFEAS' in combined:
        reason = 'FBA infeasible (GLP_NOFEAS)'
    else:
        match = re.search(r'([A-Za-z0-9_.]+Error: .+)', combined)
        if match:
            reason = match.group(1)
        else:
            tail = [line.strip() for line in combined.splitlines() if line.strip()]
            if tail:
                reason = tail[-1]

    task_name = ''
    for line in run_text.splitlines():
        if line.startswith('### name:'):
            task_name = line.split(':', 1)[1].strip().strip("'")
            break

    records.append({
        'workdir': str(workdir),
        'exit_code': exit_code,
        'reason': reason,
        'task_name': task_name,
    })

failed_df = pd.DataFrame(records)

if failed_df.empty:
    print('No failed tasks found under the Nextflow workdir root.')
else:
    summary = (
        failed_df.groupby('reason')
        .size()
        .sort_values(ascending=False)
        .rename('failed_tasks')
        .reset_index()
    )
    display(summary)
    print(f'Total failed tasks: {len(failed_df)}')
    print('\nFailures by exit code:')
    display(failed_df['exit_code'].value_counts().sort_index().rename('failed_tasks').to_frame())
## Save to csv
summary.to_csv(f'{base}/failed_tasks_summary_p4.csv', index=False)

                                              reason  failed_tasks
0  ecoli_master_sim.py: error: argument --initial...            15
1               Negative molecule levels not allowed            10
2  IndexError: cannot do a non-empty take from an...             4
3                        FBA infeasible (GLP_NOFEAS)             1

Total failed tasks: 30

Failures by exit code:

           failed_tasks
exit_code
1                    15
2                    15